# System of Linear Equations

You are given 4 systems of linear equations. You need to solve each of these systems.

Analyze each system to decide the appropriate factorization scheme. Base your answers on some properties of matrix that you figure out using the python code (not just a guess or a feeling). During this step you should also analyze if you need pioviting.

Use appropriate factoriation scheme to factorize your matrices.

Use factors to solve each system of equations.

Compare your solution for correctness with the one provide by solve() method in numpy/scipy.

## System 1

In [3]:
a = [[ 4.83563855 -0.48716942 -1.28874987 -0.17023577 -1.67652323]
     [-0.48716942  6.35914034 -0.23623091 -0.60038574  0.9641109 ]
     [-1.28874987 -0.23623091  9.38492024  1.51435365 -0.34446032]
     [-0.17023577 -0.60038574  1.51435365  1.33489675 -0.05603862]
     [-1.67652323  0.9641109  -0.34446032 -0.05603862  5.58540411]]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (<ipython-input-3-3af1ae8e42f7>, line 2)

In [ ]:
b = [1, 2, 1, 2, 1]

In [4]:
import numpy as np
from scipy.linalg import solve

a = np.array([[ 4.83563855, -0.48716942, -1.28874987, -0.17023577, -1.67652323],
              [-0.48716942,  6.35914034, -0.23623091, -0.60038574,  0.9641109 ],
              [-1.28874987, -0.23623091,  9.38492024,  1.51435365, -0.34446032],
              [-0.17023577, -0.60038574,  1.51435365,  1.33489675, -0.05603862],
              [-1.67652323,  0.9641109 , -0.34446032, -0.05603862,  5.58540411]])

b = np.array([1, 2, 1, 2, 1])

is_symmetric = np.allclose(a, a.T)
print("Is 'a' symmetric:", is_symmetric)

eigenvalues = np.linalg.eigvals(a)
is_positive_definite = np.all(eigenvalues > 0)
print("Is 'a' positive definite:", is_positive_definite)

sparsity = 1.0 - (np.count_nonzero(a) / a.size)
print("Sparsity of 'a':", sparsity)

L = np.linalg.cholesky(a)
x_cholesky = np.linalg.solve(L.T, np.linalg.solve(L, b))
print("Solution using Cholesky decomposition:", x_cholesky)

x_numpy_solve = solve(a, b)
print("Solution using numpy/scipy solve():", x_numpy_solve)

is_correct = np.allclose(x_cholesky, x_numpy_solve)
print("Are the solutions correct:", is_correct)


Is 'a' symmetric: True
Is 'a' positive definite: True
Sparsity of 'a': 0.0
Solution using Cholesky decomposition: [ 0.36230803  0.48638819 -0.13407343  1.92432408  0.21487061]
Solution using numpy/scipy solve(): [ 0.36230803  0.48638819 -0.13407343  1.92432408  0.21487061]
Are the solutions correct: True


## System 2

In [ ]:
a = [[147.88014673  61.58720137  49.77390141  86.19185778 -11.02020431]
     [ 61.58720137  79.21188958  57.64600897  92.97129568   8.64205759]
     [ 49.77390141  57.64600897 145.47555854  -0.27750402 -35.6828936 ]
     [ 86.19185778  92.97129568  -0.27750402 162.53268891  30.11833521]
     [-11.02020431   8.64205759 -35.6828936   30.11833521  39.31876182]]

In [ ]:
b = [1, 2, 1, 2, 1]

In [5]:
# Define the coefficient matrix 'a' and the right-hand side vector 'b'
a = np.array([[147.88014673,  61.58720137,  49.77390141,  86.19185778, -11.02020431],
              [ 61.58720137,  79.21188958,  57.64600897,  92.97129568,   8.64205759],
              [ 49.77390141,  57.64600897, 145.47555854,  -0.27750402, -35.6828936 ],
              [ 86.19185778,  92.97129568,  -0.27750402, 162.53268891,  30.11833521],
              [-11.02020431,   8.64205759, -35.6828936 ,  30.11833521,  39.31876182]])

b = np.array([1, 2, 1, 2, 1])

# Analyze matrix 'a'
is_symmetric = np.allclose(a, a.T)
eigenvalues = np.linalg.eigvals(a)
is_positive_definite = np.all(eigenvalues > 0)
sparsity = 1.0 - (np.count_nonzero(a) / a.size)

print("Is 'a' symmetric:", is_symmetric)
print("Is 'a' positive definite:", is_positive_definite)
print("Sparsity of 'a':", sparsity)

# Perform Cholesky decomposition and solve the system
L = np.linalg.cholesky(a)
x_cholesky = np.linalg.solve(L.T, np.linalg.solve(L, b))
print("Solution using Cholesky decomposition:", x_cholesky)

# Solve the system using numpy/scipy solve()
x_numpy_solve = solve(a, b)
print("Solution using numpy/scipy solve():", x_numpy_solve)

# Check for correctness
is_correct = np.allclose(x_cholesky, x_numpy_solve)
print("Are the solutions correct:", is_correct)

Is 'a' symmetric: True
Is 'a' positive definite: True
Sparsity of 'a': 0.0
Solution using Cholesky decomposition: [ 0.01093982  0.1696775  -0.06338488 -0.09133855  0.00364725]
Solution using numpy/scipy solve(): [ 0.01093982  0.1696775  -0.06338488 -0.09133855  0.00364725]
Are the solutions correct: True


## System 3

In [ ]:
a = [[1.64681904 0.60467877 0.30444051 0.73676928 0.69834607]
     [0.60467877 1.13522644 0.75574608 0.12606269 0.85776802]
     [0.30444051 0.75574608 1.4921206  0.8153735  0.38990932]
     [0.73676928 0.12606269 0.8153735  1.2139189  0.37597481]
     [0.69834607 0.85776802 0.38990932 0.37597481 1.06609491]]

In [ ]:
b = [1, 2, 1, 2, 1]

In [6]:
a = np.array([[1.64681904, 0.60467877, 0.30444051, 0.73676928, 0.69834607],
              [0.60467877, 1.13522644, 0.75574608, 0.12606269, 0.85776802],
              [0.30444051, 0.75574608, 1.4921206 , 0.8153735 , 0.38990932],
              [0.73676928, 0.12606269, 0.8153735 , 1.2139189 , 0.37597481],
              [0.69834607, 0.85776802, 0.38990932, 0.37597481, 1.06609491]])

b = np.array([1, 2, 1, 2, 1])

# Analyze matrix 'a'
is_symmetric = np.allclose(a, a.T)
eigenvalues = np.linalg.eigvals(a)
is_positive_definite = np.all(eigenvalues > 0)
sparsity = 1.0 - (np.count_nonzero(a) / a.size)

print("Is 'a' symmetric:", is_symmetric)
print("Is 'a' positive definite:", is_positive_definite)
print("Sparsity of 'a':", sparsity)

L = np.linalg.cholesky(a)
x_cholesky = np.linalg.solve(L.T, np.linalg.solve(L, b))
print("Solution using Cholesky decomposition:", x_cholesky)

# Solve the system using numpy/scipy solve()
x_numpy_solve = solve(a, b)
print("Solution using numpy/scipy solve():", x_numpy_solve)

# Check for correctness
is_correct = np.allclose(x_cholesky, x_numpy_solve)
print("Are the solutions correct:", is_correct)

Is 'a' symmetric: True
Is 'a' positive definite: True
Sparsity of 'a': 0.0
Solution using Cholesky decomposition: [-233635.21389462  753731.90657761 -515831.71578942  552332.88631753
 -459530.89686084]
Solution using numpy/scipy solve(): [-233635.21390632  753731.90661535 -515831.71581525  552332.88634518
 -459530.89688385]
Are the solutions correct: True


## System 4

In [ ]:
a = [[2, 0, 0, 0, 0],
     [2, 3, 0, 0, 0],
     [3, 4, 4, 0, 0],
     [4, 2, 3, 2, 0],
     [2, 2, 2, 2, 2]]

In [ ]:
b = [1, 2, 1, 2, 1]

In [15]:
from scipy.linalg import lu, solve
a = np.array([[2, 0, 0, 0, 0],
              [2, 3, 0, 0, 0],
              [3, 4, 4, 0, 0],
              [4, 2, 3, 2, 0],
              [2, 2, 2, 2, 2]])

b = np.array([1, 2, 1, 2, 1])

# Analyze matrix 'a'
is_symmetric = np.allclose(a, a.T)
eigenvalues = np.linalg.eigvals(a)
is_positive_definite = np.all(eigenvalues > 0)
sparsity = 1.0 - (np.count_nonzero(a) / a.size)

print("Is 'a' symmetric:", is_symmetric)
print("Is 'a' positive definite:", is_positive_definite)
print("Sparsity of 'a':", sparsity)

# Perform LU decomposition with partial pivoting
P, L, U = lu(a)

# Solve the system using LU factors
x_lu = np.linalg.solve(U, np.linalg.solve(L, np.dot(P, b)))
print("Solution using LU decomposition with partial pivoting:", x_lu)

# Solve the system using numpy/scipy solve()
x_numpy_solve = solve(a, b)
print("Solution using numpy/scipy solve():", x_numpy_solve)

# Check for correctness
is_correct = np.allclose(x_lu, x_numpy_solve)
print("Are the solutions correct:", is_correct)

Is 'a' symmetric: False
Is 'a' positive definite: True
Sparsity of 'a': 0.4
Solution using LU decomposition with partial pivoting: [ 0.5         0.33333333 -0.45833333  0.35416667 -0.22916667]
Solution using numpy/scipy solve(): [ 0.5         0.33333333 -0.45833333  0.35416667 -0.22916667]
Are the solutions correct: True
